apiVersion: apps/v1
kind: Deployment
metadata:
  name: p10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p10
  template:
    metadata:
      labels:
        app: p10
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p10
        ports:
        - containerPort: 80
